export const uyghurPreviewSectionItems = [
  { id: 'profile', label: 'Profile' },
  { id: 'financials', label: 'Financial Snapshot' },
  { id: 'scenarios', label: 'Buyer Scenarios' },
  { id: 'lead-model', label: 'Lead Model' },
];

export const uyghurPreviewMetrics = [
  { label: 'Asking Range', value: '$880K-$1.02M', detail: 'Mock range for preview only' },
  { label: 'TTM Revenue', value: '$1.18M', detail: 'Illustrative normalized estimate' },
  { label: 'Owner EBITDA', value: '$186K', detail: 'After supplier and labor normalization' },
  { label: 'Payback Window', value: '4.3-5.2 yrs', detail: 'Varies by buyer scenario' },
];

export const uyghurRevenueMix = [
  { label: 'Dine-in', value: 42, amount: '$496K' },
  { label: 'Takeout', value: 24, amount: '$283K' },
  { label: 'Delivery', value: 18, amount: '$212K' },
  { label: 'Catering', value: 10, amount: '$118K' },
  { label: 'Retail / Add-ons', value: 6, amount: '$71K' },
];

export const uyghurCostStructure = [
  { label: 'Food + packaging', value: 31 },
  { label: 'Labor', value: 27 },
  { label: 'Occupancy', value: 11 },
  { label: 'Marketing + admin', value: 6 },
  { label: 'Normalized operating margin', value: 25 },
];

export const uyghurScenarioCards = [
  {
    title: 'Owner-Operator',
    entryCost: '$910K',
    annualCashFlow: '$205K',
    payback: '4.4 years',
    summary: 'Best fit for a buyer willing to run the floor closely, preserve the menu identity, and tighten labor scheduling.',
    highlights: ['Hands-on staffing keeps margins strongest', 'Fastest path to payback', 'Moderate reinvestment need in systems'],
  },
  {
    title: 'Strategic Operator',
    entryCost: '$980K',
    annualCashFlow: '$231K',
    payback: '4.2 years',
    summary: 'Works for an operator who can add delivery radius, shared purchasing, and multi-unit oversight without changing the concept.',
    highlights: ['Highest upside from delivery and catering scale', 'Shared back-office support improves EBITDA', 'Requires stronger integration plan'],
  },
  {
    title: 'Absentee Sponsor',
    entryCost: '$880K',
    annualCashFlow: '$168K',
    payback: '5.2 years',
    summary: 'A passive buyer can still preserve cash flow, but depends on hiring an experienced GM and tolerating slower optimization.',
    highlights: ['Lower upside without active operating discipline', 'Most sensitive to manager quality', 'Stronger reporting layer required'],
  },
];

export const uyghurLeadModel = [
  { stage: 'Website publication', value: '$100', detail: 'One-time listing fee' },
  { stage: 'Qualified lead introduced', value: '$100', detail: 'Per lead generated by B2W' },
  { stage: 'Analysis dashboard upgrade', value: '$1,000', detail: 'Interactive buyer-facing diligence page' },
];

export const uyghurChatScript = [
  {
    ask: 'Can the current cash flow support debt service if I keep the concept mostly intact?',
    answer: 'In the owner-operator scenario shown here, the mock model leaves enough room for debt coverage if labor stays disciplined and dine-in volume remains stable.',
  },
  {
    ask: 'What are the biggest diligence risks before I make an offer?',
    answer: 'The main diligence priorities are lease transfer terms, kitchen equipment condition, and validating delivery-platform margins against bank deposits.',
  },
  {
    ask: 'I want to start at $850K with a 45-day close. How should that be framed to the owner?',
    answer: 'The agent would position that as a clean first offer tied to fast diligence completion, then defend price using occupancy risk and working-capital needs rather than generic discounting.',
  },
  {
    ask: 'Can you keep the conversation moving if the seller goes quiet?',
    answer: 'Yes. The preview agent is framed to answer common buyer questions, reinforce approved talking points, and advance negotiation steps inside owner-defined guardrails.',
  },
];
