import type {
  ClientCommunicationSubmission,
  LeadSubmission,
  ProposalSignatureSubmission,
} from './validation.js';

function esc(value: string): string {
  return value
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;');
}

function renderFields(fields: Array<[string, string]>) {
  const text = fields.map(([label, value]) => `${label}: ${value || '-'}`).join('\n');
  const html = `
    <table cellpadding="0" cellspacing="0" style="border-collapse:collapse;width:100%;">
      ${fields
        .map(
          ([label, value]) => `
            <tr>
              <td style="padding:8px 12px;border:1px solid #e5e7eb;font-weight:600;vertical-align:top;">${esc(label)}</td>
              <td style="padding:8px 12px;border:1px solid #e5e7eb;vertical-align:top;">${esc(value || '-')}</td>
            </tr>`,
        )
        .join('')}
    </table>
  `;

  return { text, html };
}

export function buildLeadEmails(submission: LeadSubmission) {
  const fields = renderFields([
    ['Pipeline', 'Lead Inquiry'],
    ['Name', submission.name],
    ['Email', submission.email],
    ['Company', submission.company],
    ['Phone', submission.phone],
    ['Website', submission.website],
    ['Inquiry Type', submission.inquiryType],
    ['ARR', submission.arrRange],
    ['Project Areas', submission.projectAreas.join(', ')],
    ['Message', submission.message],
    ['Source Page', submission.sourcePage || submission.sourcePath],
    ['Referrer', submission.referrer],
  ]);

  return {
    internal: {
      subject: `Lead Inquiry: ${submission.inquiryType} from ${submission.name}`,
      text: fields.text,
      html: `<h2>Lead Inquiry</h2>${fields.html}`,
      replyTo: submission.email,
    },
    confirmation: {
      subject: 'B2W received your inquiry',
      text:
        `Hi ${submission.name},\n\n` +
        `B2W received your inquiry about ${submission.inquiryType}. ` +
        `We will review the business context you shared and follow up by email.\n\n` +
        `Best,\nB2W`,
      html:
        `<p>Hi ${esc(submission.name)},</p>` +
        `<p>B2W received your inquiry about <strong>${esc(submission.inquiryType)}</strong>. ` +
        `We will review the business context you shared and follow up by email.</p>` +
        `<p>Best,<br/>B2W</p>`,
    },
  };
}

export function buildClientCommunicationEmails(submission: ClientCommunicationSubmission) {
  const fields = renderFields([
    ['Pipeline', 'Client Communication'],
    ['Client Name', submission.clientName],
    ['Client Email', submission.clientEmail],
    ['Company', submission.company],
    ['Project / Account', submission.projectName],
    ['Message Category', submission.messageCategory],
    ['Message', submission.message],
    ['Source Page', submission.sourcePage || submission.sourcePath],
    ['Referrer', submission.referrer],
  ]);

  return {
    internal: {
      subject: `Client Communication: ${submission.projectName}`,
      text: fields.text,
      html: `<h2>Client Communication</h2>${fields.html}`,
      replyTo: submission.clientEmail,
    },
    confirmation: {
      subject: 'B2W received your message',
      text:
        `Hi ${submission.clientName},\n\n` +
        `B2W received your message regarding ${submission.projectName}. ` +
        `We will review it and follow up by email.\n\n` +
        `Best,\nB2W`,
      html:
        `<p>Hi ${esc(submission.clientName)},</p>` +
        `<p>B2W received your message regarding <strong>${esc(submission.projectName)}</strong>. ` +
        `We will review it and follow up by email.</p>` +
        `<p>Best,<br/>B2W</p>`,
    },
  };
}

export function buildProposalSignatureEmails(submission: ProposalSignatureSubmission) {
  // Parse multi-line notes (like those generated by the Project Builder) into a structured list
  const criteriaList = submission.notes
    .split('\\n')
    .filter(Boolean)
    .map((line) => `<li style="margin-bottom: 8px;">${esc(line)}</li>`)
    .join('');

  const b2wLogoHtml = `
    <div style="margin-bottom: 30px; border-bottom: 1px solid #111; padding-bottom: 16px;">
      <h1 style="font-family: ui-sans-serif, system-ui, sans-serif; font-size: 24px; font-weight: 500; margin: 0; color: #111; letter-spacing: -0.02em;">B2W</h1>
      <p style="font-family: ui-monospace, SFMono-Regular, monospace; font-size: 11px; text-transform: uppercase; letter-spacing: 0.18em; color: #666; margin: 4px 0 0 0;">Automated Dispatch</p>
    </div>
  `;

  const detailsTable = `
    <table cellpadding="0" cellspacing="0" style="border-collapse: collapse; width: 100%; border: 1px solid #111; font-family: ui-sans-serif, system-ui, sans-serif; font-size: 14px; text-align: left;">
      <tbody>
        <tr>
          <td style="padding: 12px; border: 1px solid #111; font-family: ui-monospace, SFMono-Regular, monospace; font-size: 11px; text-transform: uppercase; letter-spacing: 0.18em; color: #555; vertical-align: top; width: 35%;">Client / Signer</td>
          <td style="padding: 12px; border: 1px solid #111; color: #111;">${esc(submission.signerName)}<br/><span style="color: #666;">${esc(submission.signerEmail)}</span></td>
        </tr>
        <tr>
          <td style="padding: 12px; border: 1px solid #111; font-family: ui-monospace, SFMono-Regular, monospace; font-size: 11px; text-transform: uppercase; letter-spacing: 0.18em; color: #555; vertical-align: top;">Company</td>
          <td style="padding: 12px; border: 1px solid #111; color: #111;">${esc(submission.company || 'Not specified')}</td>
        </tr>
        <tr>
          <td style="padding: 12px; border: 1px solid #111; font-family: ui-monospace, SFMono-Regular, monospace; font-size: 11px; text-transform: uppercase; letter-spacing: 0.18em; color: #555; vertical-align: top;">Project Type</td>
          <td style="padding: 12px; border: 1px solid #111; color: #111; font-weight: 500;">${esc(submission.proposalName)}</td>
        </tr>
      </tbody>
    </table>
  `;

  const criteriaSection = criteriaList ? `
    <div style="margin-top: 24px; border: 1px solid #111; background-color: #f9f9f9; padding: 20px;">
      <p style="font-family: ui-monospace, SFMono-Regular, monospace; font-size: 11px; text-transform: uppercase; letter-spacing: 0.18em; color: #111; margin: 0 0 16px 0;">Project Builder Criteria</p>
      <ul style="font-family: ui-sans-serif, system-ui, sans-serif; font-size: 14px; color: #333; margin: 0; padding-left: 20px; line-height: 1.5;">
        ${criteriaList}
      </ul>
    </div>
  ` : '';

  const buttonHtml = `
    <div style="margin-top: 32px;">
      <a href="${esc(submission.proposalUrl || 'https://b2w-ai.com')}" style="display: inline-block; padding: 12px 24px; background-color: #111; color: #fff; text-decoration: none; font-family: ui-sans-serif, system-ui, sans-serif; font-size: 14px; font-weight: 500;">View Full Details</a>
    </div>
  `;

  // General text fallback format
  const textFormat =
    `B2W PROPOSAL RESPONSE\n` +
    `--------------------------\n` +
    `Signer: ${submission.signerName} (${submission.signerEmail})\n` +
    `Company: ${submission.company}\n` +
    `Project: ${submission.proposalName}\n\n` +
    `CRITERIA:\n${submission.notes}\n\n` +
    `Link: ${submission.proposalUrl || 'N/A'}\n`;

  return {
    internal: {
      subject: `[Internal Alert] New Project Builder Acceptance from ${submission.company || submission.signerName}`,
      text: textFormat,
      html: `
        <div style="max-width: 600px; margin: 0 auto; padding: 20px; font-family: ui-sans-serif, system-ui, sans-serif;">
          ${b2wLogoHtml}
          <div style="background-color: #111; color: #fff; padding: 16px; margin-bottom: 24px;">
            <p style="font-family: ui-monospace, SFMono-Regular, monospace; font-size: 11px; text-transform: uppercase; letter-spacing: 0.18em; margin: 0 0 8px 0; color: #aaa;">Status: New Acceptance</p>
            <h2 style="margin: 0; font-size: 18px; font-weight: 500;">A new client has accepted a project proposal.</h2>
          </div>
          ${detailsTable}
          ${criteriaSection}
          ${buttonHtml}
        </div>
      `,
      replyTo: submission.signerEmail,
    },
    confirmation: {
      subject: `Proposal Receipt: ${submission.proposalName}`,
      text:
        `Hi ${submission.signerName},\n\n` +
        `This is a receipt confirming we successfully received your proposal acceptance for ${submission.proposalName}.\n\n` +
        `We have securely logged your business profile and selected criteria. ` +
        `A member of the team will be reaching out to you shortly via email with the finalized contract and to schedule our kickoff call.\n\n` +
        `Best,\nB2W`,
      html: `
        <div style="max-width: 600px; margin: 0 auto; padding: 20px; font-family: ui-sans-serif, system-ui, sans-serif;">
          ${b2wLogoHtml}
          <div style="border: 1px solid #111; padding: 24px; margin-bottom: 24px;">
            <h2 style="margin: 0 0 16px 0; font-size: 20px; font-weight: 500; color: #111;">Proposal Accepted</h2>
            <p style="font-size: 15px; line-height: 1.6; color: #444; margin: 0 0 16px 0;">
              Hi ${esc(submission.signerName)},<br/><br/>
              This is a receipt confirming we successfully received your non-binding proposal acceptance for <strong>${esc(submission.proposalName)}</strong>.
            </p>
            <p style="font-size: 15px; line-height: 1.6; color: #444; margin: 0;">
              We have securely logged your business profile and selected criteria. A member of our team will be reaching out to you shortly with the finalized contract and to align on next steps.
            </p>
          </div>
          ${detailsTable}
          ${criteriaSection}
          <div style="margin-top: 32px; padding-top: 24px; border-top: 1px dashed #ccc; font-size: 13px; color: #666; line-height: 1.5;">
            <p style="margin: 0;">B2W AI Solutions</p>
            <p style="margin: 4px 0 0 0;"><a href="https://b2w-ai.com" style="color: #111;">b2w-ai.com</a></p>
          </div>
        </div>
      `,
    },
  };
}
