import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';
import { listStaticSeoRoutes } from '../src/lib/seo.ts';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const root = path.resolve(__dirname, '..');
const appPath = path.join(root, 'src', 'App.tsx');
const outputPath = path.join(root, 'docs', 'seo-route-inventory.md');

const excludedStaticRoutes = new Set([
  '/app-test-1',
  '/home-test-1',
  '/solutions',
  '/solutions/how-it-works',
  '/solutions/questions',
  '/solutions/privacy',
  '/borek-g',
  '/capabilities',
  '/capabilities/marketing-data',
  '/about/process',
  '/about/team',
  '/client/narinder-sagoo',
  '/uyghur-eats',
  '/uyghur-eats-profile',
  '/uyghur-eats-valuation-model',
  '/uyghur-eats-data-room',
  '/uyghur-eats-acquisition',
  '/uyghur-eats-valuation',
]);

const excludedPrefixes = ['/client/'];

function readStaticRoutesFromApp() {
  const appSource = fs.readFileSync(appPath, 'utf-8');

  return Array.from(appSource.matchAll(/path="([^"]+)"/g))
    .map((match) => match[1])
    .filter((route) => route.startsWith('/') && !route.includes(':') && !route.includes('*'))
    .filter((route) => !excludedStaticRoutes.has(route))
    .filter((route) => !excludedPrefixes.some((prefix) => route.startsWith(prefix)))
    .sort((left, right) => left.localeCompare(right));
}

function toRelativeAssetPath(imageUrl?: string) {
  if (!imageUrl) {
    return 'None';
  }

  return imageUrl.replace(/^https:\/\/www\.b2w-ai\.com/, '');
}

const routes = listStaticSeoRoutes().sort((left, right) => left.pathname.localeCompare(right.pathname));
const routeSet = new Set(routes.map((route) => route.pathname));
const appRoutes = readStaticRoutesFromApp();
const missingCoverage = appRoutes.filter((route) => !routeSet.has(route));

if (missingCoverage.length > 0) {
  throw new Error(`Static SEO coverage is missing for: ${missingCoverage.join(', ')}`);
}

const indexableCount = routes.filter((route) => !route.robots.toLowerCase().includes('noindex')).length;
const noindexCount = routes.length - indexableCount;
const generatedAt = new Date().toISOString().slice(0, 10);

const markdown = `# SEO Route Inventory

Generated: ${generatedAt}

This file is generated by \`npm run sync:marketing-docs\`. Do not hand-edit it. Update \`src/lib/seo.ts\`, route copy, or public assets, then rerun the sync command.

## Coverage Summary

- Static SEO routes: ${routes.length}
- Indexable routes: ${indexableCount}
- Noindex routes: ${noindexCount}
- Public app routes missing static SEO coverage: none

## Favicon And Share Assets

- Canonical vector favicon: \`public/favicon.svg\`
- Generated raster favicon: \`public/favicon.png\`
- Generated 96px favicon: \`public/favicon-96x96.png\`
- Generated Apple touch icon: \`public/apple-touch-icon.png\`
- Generated ICO bundle: \`public/favicon.ico\`
- Generated manifest: \`public/site.webmanifest\`
- Default B2W share card: \`public/brand/b2w-social-card.png\`
- Clara share card: \`public/brand/clara-social-card.png\`

## Route Inventory

| Route | Title | Robots | Share Image |
| --- | --- | --- | --- |
${routes
  .map(
    (route) =>
      `| \`${route.pathname}\` | ${route.title.replace(/\|/g, '\\|')} | \`${route.robots}\` | \`${toRelativeAssetPath(route.imageUrl)}\` |`,
  )
  .join('\n')}
`;

fs.writeFileSync(outputPath, markdown, 'utf-8');
console.log(`Wrote ${path.relative(root, outputPath)}`);
