create extension if not exists pgcrypto;

create table if not exists public.jasonai_progress_versions (
  id bigint generated by default as identity primary key,
  project_id text not null default 'jason-ai',
  created_at timestamptz not null default now(),
  actor_role text not null check (actor_role in ('CEO', 'COO', 'CTO')),
  change_type text not null,
  entity_id text not null,
  change_summary text not null,
  changed_fields jsonb not null default '{}'::jsonb,
  snapshot jsonb not null,
  snapshot_hash text not null,
  timeline jsonb not null,
  analysis jsonb not null,
  model_name text,
  source text not null default 'internal-portal',
  user_agent_hash text
);

create index if not exists jasonai_progress_versions_project_created_idx
  on public.jasonai_progress_versions (project_id, created_at desc);

create index if not exists jasonai_progress_versions_project_id_idx
  on public.jasonai_progress_versions (project_id, id desc);

alter table public.jasonai_progress_versions enable row level security;

comment on table public.jasonai_progress_versions is
  'Immutable JasonAI executive-strategy snapshots, change metadata, timeline assessment, and project-manager analysis. Access is service-role only.';

